@startuml shortener

hide circle
skinparam Linetype ortho
skinparam Ranksep 60
skinparam Nodesep 100


entity "Role" as role {
    * id: <<uuid>>
    ---
    * name: string
    * createdAt: timestamp
    * editedAt: timestamp
    deletedAt: timestamp
}

entity "User" as user {
  *id : <<uuid>>
  --
  * username : text
  * email : text
  * passwordHash : text
  * createdAt: timestamp
  * editedAt: timestamp
  deletedAt: timestamp
}

entity "Link" as link {
  *id : <<uuid>>
  --
  * createdBy_id: <<FK>>
  * url: text
  * shortUrl: text
  * isAdvertisementEnabled: bool
  * createdAt: timestamp
  * editedAt: timestamp
  deletedAt: timestamp
}

entity "LinkStatistics" as linkStats {
  *id : <<uuid>>
  --
  * link_id: <<FK>>
  * region: text
  * language: text
  * createdAt: timestamp
  deletedAt: timestamp
}

entity "Advertisement" as ad {
  *id : <<uuid>>
  --
  * createdBy_id: <<FK>>
  * url: text
  * type: ENUM(VIDEO, PHOTO)
  * createdAt: timestamp
  * editedAt: timestamp
  deletedAt: timestamp
}

entity "AdvertisementStatistics" as adStats {
  *id : <<uuid>>
  --
  * advertisement_id: <<FK>>
  * createdAt: timestamp
  skippedAt: timestamp
  clickedAt: timestamp
  deletedAt: timestamp
}

user }o..|| role
user ||..o{ link
user ||..o{ ad

ad ||..o{ adStats
link ||..o{ linkStats
@enduml